CREATE DATABASE TESTDB;

USE TESTDB;

CREATE TABLE IF NOT EXISTS TESTDB.HTMLSCORES (
		         FILE_NAME  CHAR(50) NOT NULL,
		         PERSON_NAME  CHAR(50),
		         SCORE INT,
		         DATE_CREATED DATETIME,
		         DATE_RUN DATETIME,
		         PRIMARY KEY (FILE_NAME))