CREATE TABLE IF NOT EXISTS HTMLSCORES (
		         FILE_NAME  CHAR(50) NOT NULL,
		         PERSON_NAME  CHAR(50),
		         SCORE INT,
		         DATE_CREATED DATETIME,
		         DATE_RUN DATETIME,
		         PRIMARY KEY (FILE_NAME))